### ISSUE TITLE
Select all by default

### ISSUE THREAD

**Issue by Rastopapola** [nursix/eden#85]
# Status quo
All checkboxes inside **Berufsgruppe** are not selected by default:
![image](https://user-images.githubusercontent.com/35961376/80370693-f2e54000-8890-11ea-9c04-56f0ef55238b.png)

This might be confusing for users, since the tables behaves as if all checkboxes would be selected. 

# Enhancement
Auto-select all checkboxes by default, so the user will see a full table and all checkboxes checked, making them understand that unchecking a checkbox results in not-showing results from this category.

**Comment by nursix** [comment]
Sorry, but this is the wrong logic:

Selecting nothing in a filter means that the filter /does nothing/ - that's how all filters work here: if you e.g. leave the text box empty, it will not search for empty fields, but will have no effect whatsoever - and the same applies to each and every filter widget, and I want to argue that is the case in almost all web apps.

Equally, if you would pre-select all boxes, and the user would de-select them all, expecting to find those volunteers with no occupation type, they would be disappointed. That's not how it works: nothing selected means "don't apply this filter".

Further, pre-selecting all boxes means that a search query will be initiated everytime you open that page - and we don't want that unnecessary traffic, and it is unnecessary because it has the same effect as not selecting anything.

For consistency and performance reasons, I would strongly advice to leave as-is.

**Comment by nursix** [comment]
It is also quite poor UX to force the user to de-select 5 boxes in order to filter for one occupation type, rather than letting them select just one box.

That too a reason not to pre-select anything.

**Comment by Rastopapola** [comment]
>Further, pre-selecting all boxes means that a search query will be initiated everytime you open that page - and we don't want that unnecessary traffic, and it is unnecessary because it has the same effect as not selecting anything.

I was not aware of the implementation in detail. Rendering the html with pre-selected checkboxes was in my mind, not rendering and auto-selecting all boxes, e.g. using javascript, which of course causes too much traffic.

 >It is also quite poor UX to force the user to de-select 5 boxes in order to filter for one occupation type, rather than letting them select just one box.

Depends on the context and whether the user knows what to look for or what **not** to look for. In here, it might be possible that the user is interested in all volunteers, except teachers. Therefore the user needs to select all checkboxes manually, just leaving the teachers checkbox empty, for retrieving only relevant results. 

However, I see the technical aspect you stated before and agree, closing this issue.
